_BASE_: "../Base-RCNN.yaml"
MODEL:
  META_ARCHITECTURE: "DefrcnTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.5 #ubt为0.25
    LOSS: "CrossEntropy"
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NAME: "Res5ROIHeadsPseudoLab"
    LOSS: "CrossEntropy" #ubt为FocalLoss at为CrossEntropy
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
  BASE_LR: 0.00125
  WARMUP_ITERS: 0 #Defrcn为0
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("voc_2007_trainval_all1_1shot_seed0",)
  TRAIN_UNLABEL: ("voc_2007_test_all1",)
  TEST: ("voc_2007_test_all1",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.9 #待调整 ubt为0.7 at为0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996 #ubt为0.999 at为0.9996
  UNSUP_LOSS_WEIGHT: 0.5 #ubt为2.0 at为1.0
TEST:
  EVAL_PERIOD: 500
